production:
  access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] %>
  bucket: "jobsgalore"
  region: "ap-southeast-2"
  existing_remote_files: "delete"

development:
    access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
    secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] %>
    bucket: "jobsgalore"
    region: "ap-southeast-2"
    existing_remote_files: "delete"

test:
    access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
    secret_access_key: <%= ENV["S3_SECRET_ACCESS_KEY"] %>
    bucket: "jobsgalore"
    region: "ap-southeast-2"
    existing_remote_files: "delete"



